apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    chart: argo-cd
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true

  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.47.0
    helm:
      valuesObject:
        global:
          domain: "argocd.dev.local"
        server:
          extraArgs:
            - --insecure
          ingress:
            enabled: true
