apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true

  source:
    repoURL: https://github.com/mazelab/argocd-root-basics.git
    path: charts/argocd-git
    targetRevision: main
    helm:
      valuesObject:
        global:
          domain: "argocd.dev.local"