apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certManager.clusterIssuer }}-ca
  namespace: {{ .Values.namespace }}
spec:
  isCA: true
  commonName: {{ .Values.certManager.clusterIssuer }}-ca
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ .Values.certManager.clusterIssuer }}
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.clusterIssuer }}
spec:
  ca:
    secretName: root-ca-secret
