apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    automated:
      selfHeal: true

  source:
    chart: gitea
    repoURL: https://dl.gitea.com/charts/
    targetRevision: 10.6.0
    helm:
      valuesObject:
        redis-cluster:
          enabled: false
        redis:
          enabled: true
        postgresql:
          enabled: false
        postgresql-ha:
          enabled: false

        service:
          http:
            type: ClusterIP
            clusterIP: ""
            port: 80
            targetPort: 3000

        persistence:
          enabled: true
        actions:
          enabled: true
          provisioning:
            enabled: true
          # statefulset:
          #   actRunner: |-
          #     labels: "self-hosted:docker://catthehacker/ubuntu:act-latest,ubuntu-latest:docker://catthehacker/ubuntu:act-latest,ubuntu-22.04:docker://catthehacker/ubuntu:act-22.04"
        gitea:
          config:
            database:
              DB_TYPE: sqlite3
            server:
              # ROOT_URL: https://{{ .Values.gitea.hostname }}
              HTTP_PORT: 3000
              PROTOCOL: http
              DISABLE_SSH: true
              START_SSH_SERVER: false
        ingress:
          enabled: true
          tls:
            - hosts:
                - {{ .Values.gitea.hostname }}
              secretName: gitea-tls
          hosts:
            - host: {{ .Values.gitea.hostname }}
              paths:
                - path: /
                  pathType: Prefix
          annotations:
            cert-manager.io/cluster-issuer:
              {{ .Values.certManager.clusterIssuer }}
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
