apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: certmanager
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions: # Sync options which modifies sync behavior
      - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.

  source:
    repoURL: https://github.com/mazelab/argocd-root-basics.git
    path: charts/metrics
    targetRevision: {{ .Values.branch }}
    helm:
      valuesObject:
        metrics-server:
          apiService:
            insecureSkipTLSVerify: false
          extraArgs:
            kubelet-certificate-authority: "/etc/ssl/certs/ca.crt"
          extraVolumes:
            - name: "kube-root-ca"
              configMap:
                name: kube-root-ca.crt
          extraVolumeMounts:
            - name: kube-root-ca
              mountPath: /etc/ssl/certs
              subPath: ca.crt
              readOnly: true

