apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: opentelemetry-operator
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:     # Sync options which modifies sync behavior
      - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
  source:
    chart: opentelemetry-operator
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.69.0
    helm:
      valuesObject:
        replicaCount: 1
        manager:
          collectorImage:
            repository: otel/opentelemetry-collector-contrib
          serviceMonitor:
            enabled: false
          prometheusRule:
            enabled: false
            defaultRules:
              enabled: false
        ## Provide OpenTelemetry Operator kube-rbac-proxy container image.
        ##
        kubeRBACProxy:
          enabled: false
