apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  opentelemetry-demo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: opentelemetry-demo
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:     # Sync options which modifies sync behavior
      - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
  source:
    chart: opentelemetry-demo
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.110.0
    helm:
      valuesObject:
        namespace: opentelemetry-demo
        serviceAccount:
          create: false
          name: opentelemetry-demo
        prometheus:
          rbac:
            create: false
          serviceAccounts:
            server:
              create: false
              name: opentelemetry-demo
        grafana:
          rbac:
            create: false
          serviceAccount:
            create: false
            name: opentelemetry-demo
