apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: opentelemetry-collector
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:     # Sync options which modifies sync behavior
      - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
  source:
    chart: opentelemetry-collector
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.110.0
    helm:
      valuesObject:
        mode: deployment
        image:
          repository: otel/opentelemetry-collector-contrib
          tag: 0.110.0
{{/*        command:*/}}
{{/*          name: "otelcol-k8s"*/}}

        presets:
          logsCollection:
            enabled: true
            includeCollectorLogs: false
        config:
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: ${env:MY_POD_IP}:4317
                http:
                  endpoint: ${env:MY_POD_IP}:4318
          exporters:
            otlp/jaeger:
              endpoint: "jaeger-collector.jaeger:4317"  # endpoint for the Jaeger collector
              tls:
                insecure: true
          service:
            pipelines:
              traces:
                receivers: [ otlp ]
{{/*                exporters: [ debug ] #the traces can be found in otel collector pod logs. These aren't stored anywhere*/}}
                exporters:
                  [debug]
