apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true

  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.47.0
    helm:
      valuesObject:
        global:
          domain: "argocd.dev.local"
        dex:
          enabled: false
        notifications:
          enabled: false
        applicationSet:
          enabled: false
        configs:
          params:
            server.insecure: true
        server:
          ingress:
            enabled: true
            annotations:
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
              cert-manager.io/cluster-issuer: "my-ca-issuer"
            extraTls:
              - hosts:
                - argocd.dev.local
                secretName: argocd-tls
