apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: certmanager
  syncPolicy:
    automated:
      selfHeal: true

  source:
    repoURL: https://github.com/mazelab/argocd-root-basics.git
    path: charts/self-signed-cert-manager
    targetRevision: main
    helm:
      valuesObject:
        certmanager:
          global:
            crds:
              enabled: true
            leaderElection:
              namespace: certmanager

