apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    mazelab.github.io/kindpro: "external-secrets"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions: # Sync options which modifies sync behavior
      - CreateNamespace=false # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.10.3
    ignoreMissingFields: true
    helm:
      valuesObject:
        installCRDs: true
      valuesFiles:
        - values-external-secrets.yaml
