apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    automated:
      selfHeal: true

  source:
    chart: gitea
    repoURL: https://dl.gitea.com/charts/
    targetRevision: 10.3.0
    helm:
      valuesObject:
        redis-cluster:
          enabled: false
        redis:
          enabled: true
        postgresql:
          enabled: false
        postgresql-ha:
          enabled: false

        persistence:
          enabled: true
          existingClaim: local-pvc
          mountPath: /data
        gitea:
          config:
            database:
              DB_TYPE: sqlite3
            server:
              # ROOT_URL: https://{{ .Values.gitea.hostname }}
              HTTP_PORT: 3000
              PROTOCOL: http
              START_SSH_SERVER: false
        service:
          http:
            port: 80
        ingress:
          enabled: true
          tls:
            - hosts:
                - { { .Values.gitea.hostname } }
              secretName: gitea-tls
          hosts:
            - host: { { .Values.gitea.hostname } }
              paths:
                - path: /
                  pathType: Prefix
          annotations:
            cert-manager.io/cluster-issuer:
              { { .Values.certManager.clusterIssuer } }
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
