apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    automated:
      selfHeal: true

  source:
    chart: gitea
    repoURL: https://dl.gitea.com/charts/
    targetRevision: 10.3.0
    helm:
      valuesObject:
        redis-cluster:
          enabled: false
        redis:
          enabled: true
        postgresql:
          enabled: true
        postgresql-ha:
          enabled: false

        persistence:
          enabled: true
        gitea:
          config:
            server:
              # ROOT_URL: https://{{ .Values.gitea.hostname }}
              HTTP_PORT: 3000
        service:
          http:
            port: 80
        ingress:
          enabled: true
          hosts:
            - host: {{ .Values.gitea.hostname }}
              paths:
                - path: /
                  pathType: Prefix
          annotations:
            # cert-manager.io/cluster-issuer: letsencrypt-prod
