# create a namespace
apiVersion: v1
kind: Namespace
metadata:
  name: reloader
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea
